apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/ory/oathkeeper
patches:
  - target:
      kind: Application
      name: ory-oathkeeper
    patch: |-
      - op: replace
        path: /spec/source/helm/valuesObject/oathkeeper/config/authenticators/jwt/config/jwks_urls
        value:
          - https://ory.minikube.home/.well-known/jwks.json
      - op: replace
        path: /spec/source/helm/valuesObject/oathkeeper/accessRules
        value: |
          [
            {
              "id": "health-check",
              "match": {
                "url": "<http|https>://ory.minikube.home/health",
                "methods": ["GET"]
              },
              "authenticators": [{ "handler": "anonymous" }],
              "authorizer": { "handler": "allow" },
              "mutators": [{ "handler": "noop" }]
            }
          ]
