# helm:
## git or helm repo or OCI container registry
#  repo:
## helm chart version
#  targetRevision: # helm chart version
#  
#  repoValues: 
#  repoValuesBranch: 
#
#  path:
#  # or
#  chart:
dummy: "test"
