apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: mediamtx-origin-config
    namespace: mediamtx
    files:
      - mediamtx.yml
