apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../base/envoy/config/resources
patches:
  - target:
      kind: EnvoyProxy
      name: CLUSTER_NAME
    patch: |-
      - op: replace
        path: /metadata/name
        value: minikube
  - target:
      kind: GatewayClass
      name: CLUSTER_NAME-class
    patch: |-
      - op: replace
        path: /metadata/name
        value: minikube-class
      - op: replace
        path: /spec/parametersRef/name
        value: minikube
  - target:
      kind: Gateway
      name: GATEWAY_NAME
    patch: |-
      - op: replace
        path: /metadata/name
        value: minikube-envoy
      - op: replace
        path: /spec/gatewayClassName
        value: minikube-class
      - op: replace
        path: /spec/listeners/1/hostname
        value: "*.minikube.home"
      - op: replace
        path: /spec/listeners/1/tls/certificateRefs/0/name
        value: wildcard-minikube-home
