apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/ory/kratos
patches:
  - target:
      kind: Application
      name: ory-kratos
    patch: |-
      - op: replace
        path: /spec/source/helm/valuesObject/kratos/config/serve/public/base_url
        value: "https://ory.minikube.home/.ory/kratos/public/"
      - op: replace
        path: /spec/source/helm/valuesObject/kratos/config/selfservice/default_browser_return_url
        value: "https://ory.minikube.home/"
      - op: replace
        path: /spec/source/helm/valuesObject/kratos/config/selfservice/flows/login/ui_url
        value: "https://ory.minikube.home/login"
      - op: replace
        path: /spec/source/helm/valuesObject/kratos/config/selfservice/flows/registration/ui_url
        value: "https://ory.minikube.home/registration"
      - op: replace
        path: /spec/source/helm/valuesObject/kratos/config/selfservice/flows/settings/ui_url
        value: "https://ory.minikube.home/settings"
      - op: replace
        path: /spec/source/helm/valuesObject/kratos/config/selfservice/flows/recovery/ui_url
        value: "https://ory.minikube.home/recovery"
      - op: replace
        path: /spec/source/helm/valuesObject/kratos/config/selfservice/flows/verification/ui_url
        value: "https://ory.minikube.home/verification"
      - op: replace
        path: /spec/source/helm/valuesObject/kratos/config/selfservice/flows/error/ui_url
        value: "https://ory.minikube.home/error"
