apiVersion: v1
kind: Service
metadata:
  name: camera-sim
  namespace: mediamtx
spec:
  selector:
    app: camera-sim
  ports:
    - name: rtsp
      port: 8554
      targetPort: rtsp
      protocol: TCP
