apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - camera-sim-deployment.yaml
  - camera-sim-service.yaml
  - files-deployment.yaml
  - testsrc-deployment.yaml
configMapGenerator:
  - name: camera-sim-config
    namespace: mediamtx
    files:
      - mediamtx.yml=camera-sim.yml
