apiVersion: v1
kind: Service
metadata:
  name: mediamtx-replica
  namespace: mediamtx
spec:
  selector:
    app: mediamtx-replica
  ports:
    - name: hls
      port: 8888
      targetPort: hls
      protocol: TCP
    - name: webrtc
      port: 8889
      targetPort: webrtc
      protocol: TCP
    - name: webrtc-udp
      port: 8189
      targetPort: webrtc-udp
      protocol: UDP
