apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-client-provisioner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  project: argocd
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    helm:
      releaseName: nfs-subdir-external-provisioner
      values: |
        nfs:
         path: XXXXX
         server: YYYY

  destination:
    server: "https://kubernetes.default.svc"
    namespace: nfs-client-provisioner
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
