apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: home-lab
  source:
    chart: gateway-crds-helm
    repoURL: docker.io/envoyproxy
    targetRevision: 1.7.1
    helm:
      parameters:
      - name: "crds.gatewayAPI.enabled"
        value: "true"
      - name: "crds.envoyGateway.enabled"
        value: "true"
      releaseName: envoy-gateway-crds
  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
