apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-ca
  namespace: argocd
spec:
  project: argocd
  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  sources:
    - path:  base/cert-manager-ca/manifests
      repoURL: https://github.com/llegolas/gitops
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true

