apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: cluster-selfsigned-ca
 namespace: cert-manager
spec:
 secretName: cluster-selfsigned-ca-key-pair
 isCA: true
 subject:
   organizations:
     - minikube.home 
 issuerRef:
   name: selfsigned-issuer
   kind: ClusterIssuer
   group: cert-manager.io
 privateKey:
   algorithm: ECDSA
   size: 256
 commonName: "minikube.home"
 dnsNames:
 - minikube.home
