apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ultimate-mixed-apps-path-inference
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/llegolas/gitops.git
      revision: HEAD
      requeueAfterSeconds: 60
      files:
      - path: "test-appset/environments/*/helm-apps/*.yaml"
  - git:
      repoURL: https://github.com/llegolas/gitops.git
      revision: HEAD
      requeueAfterSeconds: 60     
      directories: 
      - path: "test-appset/environments/*/manifests/*"

  template:
    metadata:
      name: '{{if contains "/helm-apps" .path.path }}{{trimSuffix ".yaml" .path.filename}}{{ else if contains "/manifests/" .path.path }}{{ .path.basename }}{{ end }}'
      labels:
        app.kubernetes.io/managed-by: argocd-applicationset
    spec:
      project: default # Adjust or make dynamic based on environment label 
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 2}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
  
  templatePatch: |
    spec:
      sources:
      - repoURL: https://github.com/llegolas/gitops.git # REPLACE with your MONOREPO URL
        targetRevision: HEAD # Default targetRevision
      {{- if contains "/helm-apps" .path.path }}
        path: "test-appset/helm-chart/simple-chart/"
        helm:
          releaseName: {{trimSuffix ".yaml" .path.filename}}
          valueFiles:
            - $values/{{.path.path}}/{{.path.filename}}
      - repoURL: https://github.com/llegolas/gitops.git
        targetRevision: HEAD
        ref: values
      {{- else if contains "/manifests/" .path.path }}
        # Plain YAML or Kustomize application
        path: {{.path.path}} # The directory containing manifests
        # below might be needed
        # directory:
        #   recurse: false
      {{- end }}
