apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ultimate-mixed-apps-path-inference
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/llegolas/gitops.git
      revision: HEAD
      requeueAfterSeconds: 60
      # files:
      # - path: "test-appset/environments/*/helm-apps/*.yaml"
      directories: 
      - path: "test-appset/environments/*/manifests/*"

  template:
    metadata:
      # name: '{{- if contains .path.path "/helm-apps/" -}}helm-{{- .path.filename | trimSuffix ".yaml" -}}
      # {{- else if contains .path.path "/manifests/" -}}manifests-{{- path.basename -}}{{- end -}}'
      name: test # "{{.path.basename}}"
      labels:
        app.kubernetes.io/managed-by: argocd-applicationset
  
    spec:
      source:
        repoURL: https://github.com/llegolas/gitops.git # REPLACE with your MONOREPO URL
        targetRevision: HEAD # Default targetRevision
        path: '{{.path.path}}'
      project: default # Adjust or make dynamic based on environment label 
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 2}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
  
  # templatePatch: |
  #   spec:
  #     source:
  #       repoURL: https://github.com/llegolas/gitops.git # REPLACE with your MONOREPO URL
  #       targetRevision: HEAD # Default targetRevision
  #       # --- Conditional Source Configuration based on path segments ---
  #       {{- if contains .path.path "/helm-apps/" }}
  #       path: "test-appset/helm-chart/simple-chart/"        # Path to the chart within that repo
  #       helm:
  #         valueFiles:
  #           - {{ .path.filename }} # Path to the values.yaml within the monorepo
  #       {{- else if contains .path.path "/manifests/" }}
  #       # Plain YAML or Kustomize application
  #       path: {{.path.path}} # The directory containing manifests
  #       directory:
  #         recurse: true
  #       kustomize: {} # Explicitly enable Kustomize detection
  #       {{- end }}
