apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-ca
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: home-lab
  source:
    repoURL: https://github.com/llegolas/gitops.git
    targetRevision: main
    path: overlays/in-cluster/cert-manager/ca/resources
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
