apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  name: keycloak
  owner: keycloak
  cluster:
    name: keycloak-db
  encoding: UTF8
  localeCollate: C
  localeCType: C
