apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dns-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: home-lab
  source:
    chart: k8s-gateway
    repoURL: https://k8s-gateway.github.io/k8s_gateway/
    targetRevision: 3.4.1
    helm:
      releaseName: dns-gateway
      valuesObject:
        domain: CLUSTER_DOMAIN
        watchedResources:
          - Ingress
          - HTTPRoute
          - TLSRoute
          - GRPCRoute
        service:
          type: NodePort
          nodePort: 30053
  destination:
    namespace: kube-ingress-dns
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
