apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  source:
    helm:
      values: |
        defaultBackend:
          enabled: true
        controller:
          updateStrategy:
            type: Recreate
          extraArgs:
            enable-ssl-passthrough: true
          hostPort:
            enabled: true
          service:
            external:
              enabled: false
          watchIngressWithoutClass: true
