apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  source:
    helm:
      values: |
        configs:
          cm:
            exec.enabled: true
            kustomize.buildOptions: --enable-helm
          params:
            server.insecure: false
        crds:
          install: true
        dex:
          enabled: false
        extraObjects:
        - apiVersion: argoproj.io/v1alpha1
          kind: AppProject
          metadata:
            name: argocd
            namespace: argocd
          spec:
            clusterResourceWhitelist:
            - group: '*'
              kind: '*'
            description: Argocd Project
            destinations:
            - namespace: '*'
              server: '*'
            orphanedResources:
              warn: false
            sourceRepos:
            - '*'
        global:
          domain: argocd.minikube.home
        server:
          certificate:
            enabled: true
            issuer:
              group: cert-manager.io
              kind: ClusterIssuer
              name: ca-issuer
          config:
            repositories: |
              - type: git
                url: https://github.com/llegolas/gitops.git
              - name: argo-helm
                type: helm
                url: https://argoproj.github.io/argo-helm
          configEnabled: true
          ingress:
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: HTTPS
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
            enabled: true
            tls: true

