apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-client-provisioner
spec:
  source:
    helm:
      values: |
        nfs:
          path: /srv/nfs/k8s
          server: 192.168.39.1
