apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/argocd
  - ../../base/nfs-client-provisioner

patches:
  - path: application-nfs-client-provisioner.yaml
    target: 
      kind: Application
      name: nfs-client-provisioner
  - path: application-argocd.yaml
    target:
      kind: Application
      name: argocd

