apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - turn-secret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
configMapGenerator:
  - name: mediamtx-replica-config
    namespace: mediamtx
    files:
      - mediamtx.yml
