apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: poc-admin-route
  namespace: envoy-keycloak-poc
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: envoy-gateway-system
      name: GATEWAY_NAME
      sectionName: https-terminated
  hostnames:
    - poc.CLUSTER_DOMAIN
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /admin
      backendRefs:
        - group: ""
          kind: Service
          name: admin-service
          port: 8080
          weight: 1
    - matches:
        - path:
            type: Exact
            value: /oauth2/callback-admin
        - path:
            type: Exact
            value: /oauth2/logout-admin
      backendRefs:
        - group: ""
          kind: Service
          name: admin-service
          port: 8080
          weight: 1
