apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend-apps.yaml
  - ca-bundle.yaml
  - backend-keycloak.yaml
  - backendtlspolicy-keycloak.yaml
  - httproute-public.yaml
  - httproute-app.yaml
  - httproute-admin.yaml
  - httproute-api.yaml
  - httproute-dashboard.yaml
  - securitypolicy-app.yaml
  - securitypolicy-admin.yaml
  - securitypolicy-api.yaml
  - securitypolicy-dashboard.yaml
