apiVersion: apps/v1
kind: Deployment
metadata:
  name: livekit-redis
  namespace: livekit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livekit-redis
  template:
    metadata:
      labels:
        app: livekit-redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
