apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../base/mediamtx/replicas/resources
patches:
  - target:
      kind: Deployment
      name: mediamtx-replica
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mediamtx-replica
      spec:
        template:
          spec:
            containers:
              - name: mediamtx
                env:
                  - name: MTX_WEBRTCICESERVERS2_0_URL
                    value: turn:192.168.39.135:30478?transport=udp
